#!/bin/sh

gnuplot -persist << EOF
set term postscript enhanced color "Times-Roman" 26
set autoscale
set key right top
set pointsize 1
set xlabel "t"
set ylabel "r"
set xrange [0:5000]
set yrange [0:1]
set output "r-compare.eps"
plot "r_time1.dat" u 1:2 t "ra1" w p lt 1 pt 7 ,\
"r_time1.dat" u 1:5 t "rb1" w p lt -1 pt 7,\
"r_time2.dat" u 1:2 t "ra2" w p lt 1 pt 7 lc rgb "green",\
"r_time2.dat" u 1:5 t "rb2" w p lt -1 pt 7 lc rgb "blue"

EOF


